### ISSUE TITLE
Advice on warning message

### ISSUE THREAD

**Issue by samkleeman1** [cancerit/dockstore-cgpwxs#13]
Hi,

Thanks so much for all your work making these pipelines publicly available. I have been using the dockstore-cgpmap + dockstore-cgpwxs to process some exome sequencing data. I believe I have followed the instructions in the readme and have been running the docker containers using singularity. On running dockstore-cgpwxs, I noticed a number of warning messages in the log file that I did not fully understand (copied below) and was wondering if you would be able shed some light on what they mean.

Many thanks,

Sam Kleeman

```
Starting CaVEMan_annot
+ set +x
+ bash -c '/usr/bin/time -f command:%C\\nreal:%e\\nuser:%U\\nsys:%S\\npctCpu:%P\\ntext:%Xk\\ndata:%Dk\\nmax:%Mk\\n -o 12912/timings/WXS_EGAR00001059171_587220_vs_EGAR00001059227_587221.time.CaVEMan_annot AnnotateVcf.pl -t -c 12912/reference_files/vagrent/vagrent.cache.gz  -i 12912/EGAR00001059171_587220_vs_EGAR00001059227_587221/caveman/EGAR00001059171_587220_vs_EGAR00001059227_587221.flagged.muts.vcf.gz  -o 12912/EGAR00001059171_587220_vs_EGAR00001059227_587221/caveman/EGAR00001059171_587220_vs_EGAR00001059227_587221.annot.muts.vcf'
FILTER field at 1:1192278 ..  The filter(s) [SR] not listed in the header.
Warning: Duplicate entries, for example 1:1116222
Use of uninitialized value $value in concatenation (.) or string at /opt/wtsi-cgp/lib/perl5/Vcf.pm line 2960.
Use of uninitialized value $value in concatenation (.) or string at /opt/wtsi-cgp/lib/perl5/Vcf.pm line 2960.
Warning: Duplicate entries, for example 1:1116222
FILTER field at 1:1192278 ..  The filter(s) [SR] not listed in the header.
Package results

Workflow end: Mon Apr  2 11:57:03 UTC 2018
```

**Comment by keiranmraine** [comment]
There are several warnings here so I'll break them down:

* `Warning: Duplicate entries, for example 1:1...` - Nothing to worry about, VCF complains about items with the same location even if the ALT value is different.  In CaVEMan (and Pindel) we expect these.
* `Use of uninitialized value $value in concatenation ` - noise from a poor module (not ours)
* `The filter(s) [SR] not listed in the header` - Check the final VCF file, I'm pretty sure this is in the header.

Let me know the outcome of checking the header as I'm sure I've also been down this rabbit hole.
